### ISSUE TITLE
count_gotal undeclared

### ISSUE THREAD

**Issue by mstram** [RTimothyEdwards/magic#11]
When trying to build http://opencircuitdesign.com/magic/archive/magic-8.3.3.tgz

CmdCD.c: In function ‘CmdDrc’:c:3376:10: error: ‘
count_gotal undeclared (first use in this function)

=======================
lsb_release -a

Distributor ID: Debian
Description:    Debian GNU/Linux 8.11 (jessie)
Release:        8.11
Codename:       jessie

**Comment by RTimothyEdwards** [comment]
Thanks for reporting the typo.  I have fixed it in the repo and the github mirror will be updated in about 12 hours.

However, note that the typo shows up only when compiling the non-Tcl/Tk version of magic.  I generally don't recommend that, as you lose a lot of capabilities that are in the Tcl/Tk version.  You would need the tcl-devel and tk-devel packages installed for the configure script to recognize that it can compile the Tcl/Tk support.

Regards,
Tim
