### ISSUE TITLE
Why is `ext2spice rthresh` an integer?

### ISSUE THREAD

**Issue by hpretl** [RTimothyEdwards/magic#110]
`magic` is reporting an error when trying to set

`ext2spice rthresh 0.01` because it wants an integer. `ext2spice cthresh 0.01` works as expected.

Any reason why one can't set the resistor threshold to below 1Ohm?

**Comment by RTimothyEdwards** [comment]
I expect there has been no attempt to make a finer resolution for more modern processes because there aren't any tools that use the lumped resistance value.  IRSIM could probably make use of it, but doesn't, that I know of.

**Comment by hpretl** [comment]
Got it, thanks!
