### ISSUE TITLE
Place Instance

### ISSUE THREAD

**Issue by mousaalqawasmi** [RTimothyEdwards/magic#144]
Hello,

This is not an issue. I 'm trying to use the place instance command.

For example:

place instance xnor2.mag

My format here is incorrect.

Thanks,

Mousa

**Comment by RTimothyEdwards** [comment]
There is no such command in magic.  See the online documentation at http://opencircuitdesign.com/magic/ for the command reference.

**Comment by mousaalqawasmi** [comment]
Thanks.

**Comment by RTimothyEdwards** [comment]
The command you want, presumably, is `getcell`.
