### ISSUE TITLE
[Feature request] Magic VLSI does not handle non default rules

### ISSUE THREAD

**Issue by armleo** [RTimothyEdwards/magic#151]
I load the DEF + LEF then output a GDS. The non default rules are ignored and following message is displayed:

<img width="819" alt="Screen Shot 2022-03-31 at 15 57 34" src="https://user-images.githubusercontent.com/7474152/161049592-282b84e8-ca95-42bd-90de-2407b8a2591b.png">

DEF:
<img width="393" alt="Screen Shot 2022-03-31 at 15 56 30" src="https://user-images.githubusercontent.com/7474152/161049432-0f033390-e71b-41b2-9c6d-05d06d7f935c.png">

GDS:
<img width="421" alt="Screen Shot 2022-03-31 at 15 55 33" src="https://user-images.githubusercontent.com/7474152/161049295-dc0698bb-bc72-4552-9dff-131f82bb3845.png">

Is there any hope for this feature to be properly handled? I need this for the proper handling of custom GPIO template (like Caravan) routing.

**Comment by RTimothyEdwards** [comment]
What version of magic?  I added NONDEFAULTRULE handling recently (as in earlier this week).  However, your screenshot above makes it look like your rule is defined in a LEF file but used in a DEF file.  I think right now the LEF file parser doesn't recognize the keyword.  It would be easy enough to add.  A workaround is to move the NONDEFAULTRULE definition from the LEF file to the DEF file.

**Comment by armleo** [comment]
Yes it was in lef. I will try making the ndr change in def.

**Comment by RTimothyEdwards** [comment]
I have pushed an update to magic on opencircuitdesign.com that implements parsing NONDEFAULTRULE sections in a LEF file.  It is provisional and untested.  If you would like to post your LEF and DEF file, it would help me debug any issues with it.

**Comment by armleo** [comment]
There is two test cases: a and b.

**Comment by armleo** [comment]
@RTimothyEdwards The new version with LEF NDR does not work: 

```
commit 37fec8a06a61895943a0050fb3e168d1d8692440 (HEAD -> master, origin/master, origin/HEAD)

Author: Tim Edwards <tim@opencircuitdesign.com>

Date:   Thu Mar 31 10:23:39 2022 -0400



    Tentative implementation of parsing NONDEFAULTRULE definitions in

    a LEF file (complementary to the implementation recently added to

    the DEF file parser).
```
D test case. LEF non default rule. DEF non default rule applied.

[d.zip](https://github.com/RTimothyEdwards/magic/files/8391785/d.zip)

**Comment by armleo** [comment]
I updated both. Used this as reference: https://www.ispd.cc/contests/18/lefdefref.pdf

It looks like its complaining about syntax error. But it's valid syntax according to above mentioned PDF.

[d.zip](https://github.com/RTimothyEdwards/magic/files/8391852/d.zip)

**Comment by RTimothyEdwards** [comment]
Yes, I said the code was completely untested and unverified.

**Comment by RTimothyEdwards** [comment]
I corrected the error in the LEF read of NONDEFAULTRULES and it works now for your test input.  Various aspects of the NONDEFAULTRULE seem pretty ambiguous to me in the LEF/DEF reference, so if you see anything that seems to be implemented wrong, just let me know.

**Comment by RTimothyEdwards** [comment]
I will close this issue now;  if there are any issues with details of the implementation, please create a new issue for them.
