### ISSUE TITLE
Magic crashes uppon parasitics extraction

### ISSUE THREAD

**Issue by Unkraut3** [RTimothyEdwards/magic#159]
Hello,

I have a design and would like to extract the parasitics. The design is contained in the following file: [tia.zip](https://github.com/RTimothyEdwards/magic/files/8470766/tia.zip). The top cell is **tia_core.mag**.

The commands given to magic are:

`set NAME [cellname list self]; select top cell; flatten "[list $NAME]_flat"; load "[list $NAME]_flat"; select top cell;`
`extract do resistance; extract all; ext2sim labels on; ext2sim; extresist tolerance 10;`
`extresist all;`

The last command causes the crash.

**Comment by RTimothyEdwards** [comment]
@Unkraut3 :  I just pushed a fix for this to the opencircuitdesign.com respository.  The problem had to do with the use of a varactor device, which was not anticipated in one spot in the extresist code.  I noticed that although that fixed the segfault, there is still some error in extracting one of the nets (not related to varactors, apparently).  So I expect that this is not the last I will hear from you about extresist. . .

**Comment by Unkraut3** [comment]
Well, indeed :). Magic no longer crashes. However, the next commands after extresist on my list would be:

`ext2spice lvs; ext2spice cthresh 0.1; ext2spice rthresh 10; ext2spice extresist on;`
`ext2spice -o "pex_\[list $NAME\].spice";`

Extresist complains about errors  but does not say what is going wrong. 

ext2spice then complains about:  `Device subckt sky130_fd_pr__cap_var_lvt at (-2786, 1498) overlaps device with incompatible number of terminals (3 vs. 2)!`

I'm not sure, shall we close this issue and I open a new one for the ext2spice issue? After all magic no longer crashes 

Also is the generated spice now valid or not?

**Comment by Unkraut3** [comment]
This issue is solved, closing the issue.
