### ISSUE TITLE
Regression: Extract all causes freeze in magic 8.3.304

### ISSUE THREAD

**Issue by Unkraut3** [RTimothyEdwards/magic#166]
In magic 8.3.304 the command `extract all` causes magic to stop responding. Please find attached a small layout for testing: [pll_osccell.zip](https://github.com/RTimothyEdwards/magic/files/8715278/pll_osccell.zip) (Top cell: `pll_osccell.mag`). After opening the circuit enter the command `extract all`. The issue was reproducible also with another layout, so seems not to depend on the layout.

**Comment by RTimothyEdwards** [comment]
Noted, and working on it.  Thanks for the reproducible example.

**Comment by Unkraut3** [comment]
Thank you! Now the command works again!
