### ISSUE TITLE
Magic segfault

### ISSUE THREAD

**Issue by killruana** [RTimothyEdwards/magic#2]
Since commit 2046318942f7cf4b379fd956ce8f764c0a969343, magic segfault when used with qflow

> magic -dnull -noconsole  migrate_ALU.tcl
> 
> Magic 8.2 revision 101 - Compiled on Fri 01 Nov 2019 04:55:42 PM CET.
> Starting magic under Tcl interpreter
> Using the terminal as the console.
> Using NULL graphics device.
> Processing system .magicrc file
> Input style lambda=0.20(p): scaleFactor=20, multiplier=1
> Contact size value ignored (using GDS generation rules).
> Contact size value ignored (using GDS generation rules).
> Contact size value ignored (using GDS generation rules).
> Contact size value ignored (using GDS generation rules).
> Contact size value ignored (using GDS generation rules).
> Contact size value ignored (using GDS generation rules).
> 4 Magic internal units = 1 Lambda
> Loading "migrate_ALU.tcl" from command line.
> Root cell box:
>            width x height  (   llx,  lly  ), (   urx,  ury  )
> 
> microns:    0.00 x 0.00    (  0.00,  0.00 ), (  0.00,  0.00 )
> lambda:     0.00 x 0.00    (  0.00,  0.00 ), (  0.00,  0.00 )
> internal:      0 x 0       (     0,  0    ), (     0,  0    )
> Reading LEF data from file /home/killruana/opt/eda/qflow/share/qflow/tech/osu035/osu035_stdcells.lef.
> This action cannot be undone.
> LEF read, Line 16 (Message): Unknown keyword "OBS" in LEF file; ignoring.
> LEF read, Line 17 (Message): Unknown keyword "PIN" in LEF file; ignoring.
> LEF read, Line 207 (Message): Defines site corner (ignored)
> LEF read, Line 213 (Message): Defines site IO (ignored)
> LEF read, Line 219 (Message): Defines site core (ignored)
> Moving label "CLK" from metal1 to m2contact in cell DFFNEGX1.
> Moving label "CLK" from metal1 to m2contact in cell DFFNEGX1.
> Moving label "A" from metal1 to m2contact in cell XNOR2X1.
> LEF read: Processed 3179 lines.
> Cannot open input file /home/killruana/opt/eda/magic/lib/magic/tutorial/ALUHÄ▒Ã (No such file or directory).
> Scaled magic input cell ALU geometry by factor of 2
> Processing timestamp mismatches: FILL, INVX1, NOR2X1, NAND2X1, OR2X2, AOI21X1, XNOR2X1, DFFPOSX1, CLKBUF1, AND2X2, BUFX2, OAI21X1, NAND3X1, XOR2X1, NOR3X1.
> Segmentation fault (core dumped) 
> magic failed with exit status 139
> Premature exit.

Note the garbage characters at the end of the filename in the log line `Cannot open input file /home/killruana/opt/eda/magic/lib/magic/tutorial/ALU`

See this line : https://github.com/RTimothyEdwards/magic/blob/2046318942f7cf4b379fd956ce8f764c0a969343/lef/lefWrite.c#L110
if the condition is false, the variable locsuffix is never initialized, causing the crash

**Comment by RTimothyEdwards** [comment]
Thanks for the bug report.  I fixed it;  the github repo will update overnight.
---Tim
