### ISSUE TITLE
Magic mangles GDS, creates met2 out of met1, claims DRC error

### ISSUE THREAD

**Issue by growly** [RTimothyEdwards/magic#201]
I generate a GDS that has metal 1, a via, and metal 2:

![image](https://user-images.githubusercontent.com/125257/202609674-f6ac6fe5-6dec-4894-b174-0a00743b83e2.png)

I load magic, read the GDS, and inspect. It has created a big metal2 box in the same place?

![image](https://user-images.githubusercontent.com/125257/202609823-94e8390a-52d2-4d8a-ae03-6d2e92c19aa1.png)

I export the GDS from magic and can confirm the oddity in klayout:

![image](https://user-images.githubusercontent.com/125257/202609941-dee82d13-8e1f-4a62-adcd-e8af65b25615.png)

Not sure what's going on here - any advice?

**Comment by RTimothyEdwards** [comment]
My suspicion is that it is an error in the "copyup" rules for bare contacts in the tech file.  It's also possible that using the "gds flatten true" option in magic before reading the GDS might be a workaround.  Magic handles contacts differently from other tools.

**Comment by growly** [comment]
Here's the same thing happening again with the `-d XR` flag (`-d OGL` does bad things on my machine, though I thought I'd compiled it with opengl):

![image](https://user-images.githubusercontent.com/125257/202833966-8c1732cb-bed1-4f5b-b175-4931b3263cf4.png)

The unadulterated GDS is attached: [library.gds.zip](https://github.com/RTimothyEdwards/magic/files/10046036/library.gds.zip)


I can recreate on the open_pdks issue tracker if you'd like?

**Comment by RTimothyEdwards** [comment]
You've made your VIA1 contact cuts too large.  The VIA1 size is 0.15um x 0.15um, not 0.17um x 0.17um.
Magic is attempting to satisfy the minimum surround rule on metal1 and metal2 on a correctly-sized via, which is why the contact comes out larger when imported into magic.

**Comment by growly** [comment]
Wow, incredible. Thank you!

**Comment by growly** [comment]
Wait, I made them  0.15x.15 and I still see this. Attached is an updated GDS.

![image](https://user-images.githubusercontent.com/125257/203027778-ca8970bf-1f85-49ff-8f97-ff2b232647b7.png)
(please excuse the broken routing - unless that could be part of the problem?)

![image](https://user-images.githubusercontent.com/125257/203027959-b7545d36-5e71-410e-96da-39a02c1dc49b.png)

[library.gds.zip](https://github.com/RTimothyEdwards/magic/files/10055656/library.gds.zip)

Interestingly it doesn't happen over here?

![image](https://user-images.githubusercontent.com/125257/203028387-c829e570-efd8-4c97-a5cb-4da23218acc8.png)

**Comment by RTimothyEdwards** [comment]
The full set of via1 rules is that via1 size is 0.15um x 0.15um, must be surrounded on two sides by 0.055um metal1 and 0.055um metal2, and two opposite sides by 0.085um metal1 and 0.085um metal2.  Your surrounds are 0.03um and 0.06um, not 0.055um and 0.085um.

**Comment by growly** [comment]
Got it. Is there a way to have magic simply report DRC errors for this instead of trying to fix it like so?

**Comment by RTimothyEdwards** [comment]
In this case, not really.  Magic isn't really trying to "fix it".  Magic defines contacts as an area to be filled (by algorithm) with contact cuts.  To work with that definition, magic needs to have a minimum contact defined as the cut area plus the minimum amount of surrounding metal on both top and bottom.

**Comment by growly** [comment]
Ok, makes sense now. Thanks!
