### ISSUE TITLE
Add `ANTENNAGATEAREA` for abstract lef views

### ISSUE THREAD

**Issue by kareefardi** [RTimothyEdwards/magic#236]
Magic is capable of writing a lef file with `ANTENNAGATEAREA` but only without `-hide` (non-abstract). It is beneficial to have it also in abstract lef view. See https://github.com/The-OpenROAD-Project/OpenLane/issues/1737 for more details

**Comment by RTimothyEdwards** [comment]
There is nothing in the code that suggests that it should only write `ANTENNAGATE` when the `-hide` option is not selected.  Do you have a reproducible example?

**Comment by kareefardi** [comment]
@RTimothyEdwards [reproducible.tar.gz](https://github.com/RTimothyEdwards/magic/files/11331289/reproducible.tar.gz)

**Comment by RTimothyEdwards** [comment]
Must be that there is no search in the hidden area for diffusion and poly.  I'll take  a look at it.

**Comment by RTimothyEdwards** [comment]
@kareefardi :  Fixed in version 8.3.395.

**Comment by kareefardi** [comment]
Abstract lef has `ANTENNAGATEAREA` now.
