### ISSUE TITLE
magic extraction cannot discern nfet_03v3 from nfet_03v3_dw in GF180MCUC

### ISSUE THREAD

**Issue by spnadig** [RTimothyEdwards/magic#239]
@RTimothyEdwards  -  attached is a gds file with 2 kinds of inverters with nfets. One with DNWELL and the other without - which should correspond to nfet_03v3_dw and nfet_03v3 respectively. The extracted netlist (attached with extraction script used) however shows same devices (nfet03v3) for both cases. 
GF lists them to be seperate devices - as they must be mapped to different models -

![image](https://user-images.githubusercontent.com/124022677/233755447-3396e223-fd0a-403e-9c39-f45344e69f48.png)

![image](https://user-images.githubusercontent.com/124022677/233755435-c7f0b1a1-5111-4b15-a6ac-115d2fb36836.png)

[inv_dnwTest.zip](https://github.com/RTimothyEdwards/magic/files/11299997/inv_dnwTest.zip)

**Comment by spnadig** [comment]
@proppy

**Comment by proppy** [comment]
Looks like the spice deck also use `nmos_3p3` and not `nfet03v3` as the naming convention, see:
https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_pr/blob/main/models/ngspice/smbb000149.ngspice

@mithro can you link to the document that specify authoritatively the name of the primitive.

/cc @atokmabrains

**Comment by atorkmabrains** [comment]
@proppy It's 'nfet_03v3' in here:

https://github.com/efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr/tree/main/models/ngspice

Google repo is not up to date.

**Comment by mithro** [comment]
https://bit.ly/gf180mcu-names

**Comment by RTimothyEdwards** [comment]
The model name is the same whether or not the device is in deep nwell or not, so why even make the distinction?

**Comment by spnadig** [comment]
Oh I was under the impression that models change with DNWELL given GF classifies them as different devices in their list?

**Comment by RTimothyEdwards** [comment]
@spnadig :  The first table that you posted has a column for "Model Name" that indicates that the same model is used for both the device inside and outside of deep nwell.  I have not looked at it carefully;  maybe the device is just the underlying FET device?  There might be additional components in the subcircuits (i.e., does the deep nwell device have additional terminals and/or diode components representing the deep nwell and substrate connections?).

**Comment by spnadig** [comment]
No there are no additional connections - it just has DNWELL layer and guard ring (which has 2 additional layers) around a typical nfet

**Comment by RTimothyEdwards** [comment]
@spnadig :  I've used PDKs in the past where the deep nwell device models have additional connections representing the deep nwell and substrate in addition to the pwell and diffusion.  That makes them 5- and 6- terminal devices.  But in this case, I just looked at the GF SPICE models;  there are no subcircuit models for the devices in deep nwell.
