### ISSUE TITLE
error: non-void function 'efNodeMerge' should return a value

### ISSUE THREAD

**Issue by ryandesign** [RTimothyEdwards/magic#244]
magic 8.3.396 and later fail to build:

```
EFbuild.c:1791:2: error: non-void function 'efNodeMerge' should return a value [-Wreturn-type]
        return;
        ^
```

**Comment by RTimothyEdwards** [comment]
My apologies.  I had this fix on my end for I don't know how long, and apparently forgot to push it.  I just did a push, so it is now correct in opencircuitdesign.com and will be fixed on github by tomorrow.

**Comment by ryandesign** [comment]
Thanks, 8.3.400 built fine.
