### ISSUE TITLE
Segmentation fault when running *watch active demo

### ISSUE THREAD

**Issue by gkamendje** [RTimothyEdwards/magic#271]
I get a segmentation fault when running `*watch active demo` or `*watch metal1 demo`. 
I am running Magic `8.3.434-1-g656b5db` on Ubuntu 22.04.3/WSL. I saw the same behavior on CentOs7 with  `8.3.435`. 
To reproduce: 
```
/path_to_magic/magic/8.3.434-1-g656b5db/bin/magic maint2a
```
Then either type the command `*watch active demo` or `*watch metal1 demo`

**Comment by RTimothyEdwards** [comment]
Duly noted, and I can reproduce the crash condition.  I just fixed it in the code, and will push it along with some other code edits I have planned for today.

Meanwhile, you can work around the issue by forcing the layout to be editable:

```
magic maint2a
cellname writeable maint2a true
select top cell
edit
*watch active demo
```

**Comment by gkamendje** [comment]
Copying maint2a to a local writable directory also works. Thanks for the hint.
