### ISSUE TITLE
Layout Window not opening in macOS(Sonoma)

### ISSUE THREAD

**Issue by pingu-73** [RTimothyEdwards/magic#277]
I followed the instructions in the macOS install file. But when i run magic command in terminal it only opens **magic console window** and not the **layout window**.

<img width="884" alt="Screenshot 2023-10-31 at 11 40 50 AM" src="https://github.com/RTimothyEdwards/magic/assets/121669947/7c215d5c-9f9b-479f-b7f9-399129607559">

**Comment by d-m-bailey** [comment]
@pingu-73 Do you have `XQuartz` running?

**Comment by pingu-73** [comment]
@d-m-bailey i've XQuartz installed. Do i need to run it before opening magic?

**Comment by pingu-73** [comment]
on running **./scripts/configure_mac** summary is the following
<img width="1051" alt="Screenshot 2023-10-31 at 6 12 49 PM" src="https://github.com/RTimothyEdwards/magic/assets/121669947/6b3cd560-2894-4eee-8232-43af4156faf9">

**Comment by RTimothyEdwards** [comment]
@pingu-73 :  Huh.  Everything looks fine right up to the point where it says "using NULL graphics".  What was the command line you used to start magic?  Do you get a different result if you use `magic -d OGL` or `magic -d XR`?

**Comment by d-m-bailey** [comment]
@pingu-73 Yes, XQuartz needs to be active.

**Comment by pingu-73** [comment]
@d-m-bailey even after activating XQuartz i'm getting same result

<img width="904" alt="Screenshot 2023-10-31 at 7 01 26 PM" src="https://github.com/RTimothyEdwards/magic/assets/121669947/0437afca-9898-40ca-b3e5-4eea328a8498">

**Comment by d-m-bailey** [comment]
Any thing at the start of the console log file?

**Comment by pingu-73** [comment]
@d-m-bailey 
<img width="904" alt="Screenshot 2023-10-31 at 6 59 20 PM" src="https://github.com/RTimothyEdwards/magic/assets/121669947/64a83712-1542-46f6-9973-a3c08e10c792">

**Comment by d-m-bailey** [comment]
As @RTimothyEdwards says, it shouldn't say `Using NULL graphics device`. Did you try `magic -d OGL` or `magic -d XR`

**Comment by d-m-bailey** [comment]
Did you get any error messages when following the  `INSTALL_MacOS.md` instructions?

**Comment by pingu-73** [comment]
@RTimothyEdwards @d-m-bailey  using `magic -d OGL` gives segmentation fault but `magic -d XR` doesn't shows any error. Also i didn't get any error message while following `INSTALL_MacOS.md`
<img width="550" alt="Screenshot 2023-11-01 at 12 57 17 AM" src="https://github.com/RTimothyEdwards/magic/assets/121669947/42b40d23-b140-464b-83c8-30bc0d31ac3d">

<img width="550" alt="Screenshot 2023-11-01 at 12 57 50 AM" src="https://github.com/RTimothyEdwards/magic/assets/121669947/35d5ed91-dbe1-44e5-b6ba-7144c042f17a">

**Comment by RTimothyEdwards** [comment]
Type `export DISPLAY=:0` on the command line before running magic and see if that causes a window to pop up.  I worked through this issue with somebody else two months ago and they had the same issue that magic would start but not generate a window, and it didn't generate an error, either.

**Comment by pingu-73** [comment]
@RTimothyEdwards now i'm not even able to open magic console
<img width="447" alt="Screenshot 2023-11-01 at 9 13 43 AM" src="https://github.com/RTimothyEdwards/magic/assets/121669947/0b961ad5-0c6c-44b4-a60c-ac79d230df10">

**Comment by pingu-73** [comment]
@RTimothyEdwards i've solved this issue and made few changes in macOS install file can you review those changes and merge them.
[PR #278 ](https://github.com/RTimothyEdwards/magic/pull/278)
