### ISSUE TITLE
DBtpaint2.c:529 please review of 'break' keyword location

### ISSUE THREAD

**Issue by dlmiles** [RTimothyEdwards/magic#339]
https://github.com/RTimothyEdwards/magic/blob/master/database/DBtpaint2.c#L529

Please review the indentation of this  `break` keyword, as it makes the containing `for()` loop redundant and reduces it to an `if(TT_TECHDEPBASE < DBNumUserLayers)` statement.

Maybe a comment left in the area to say this is ok/intentional with some insight might help the next reader.

SonarCloud
Change this loop body so that it can be executed more than once.
https://sonarcloud.io/project/issues?open=AZJB16rNNGfDNup0RiZp&id=dlmiles_magic

**Comment by RTimothyEdwards** [comment]
Clearly wrong, thanks.  I will fix it.  I'm not even sure the `break` should be there at all because it's possible to define a "stacked" contact type that always exists on more than two planes.

**Comment by RTimothyEdwards** [comment]
Fixed in magic version 8.3.509.  I'm not aware of any problems having to do with this code, so I have no idea what impact it has, if any.
