### ISSUE TITLE
View only inserted clock buffers post CTS in MAGIC layout window.

### ISSUE THREAD

**Issue by nickson-jose** [RTimothyEdwards/magic#37]
Hi Tim,
Is there anyway to view only the inserted clock buffers post CTS in Magic layout window?

-Nickson

**Comment by RTimothyEdwards** [comment]
This could be done by a (relatively) simple Tcl script if there is some unique naming convention used by the CTS for the buffer names.  First, make sure you do "def read <cellname> -labels" to make sure that all nets are labeled.  You can have the script either read the DEF file or the .mag file to get all the label names, filter them for the ones that are specific to the clock tree, and then run "select net <name>" for each of them.

I have only ever done this by hand on small designs, but another useful feature is to color the nets.  Doing "select more ..." will keep selecting more things without unselecting the previous ones, but doing "select feedback <style>" will paint over the selection with a color; such as "select feedback yellow1" or "select feedback white".  If the CTS nets are named according to hierarchy (I know qflow does this), then you can make the different hierarchical levels of the clock network show in different colors.
