### ISSUE TITLE
Segmentation fault (core dumped) 

### ISSUE THREAD

**Issue by harshithsn** [RTimothyEdwards/magic#86]
I got segmentation fault (core dumped) error by loading `sky130A.tech` file.
`magic -T sky130A.tech `
I have attached `sky130A.tech` file in below link, Please resolve my issue

[sky130A.zip](https://github.com/RTimothyEdwards/magic/files/6949060/sky130A.zip)

Thank You

**Comment by RTimothyEdwards** [comment]
Probably your version of magic is way out of date.

**Comment by harshithsn** [comment]
> Probably your version of magic is way out of date.

@RTimothyEdwards sir, are you able to open magic with `sky130A.tech` technology file?

**Comment by RTimothyEdwards** [comment]
Yes, I can open magic with your sky130A.tech.  What version of magic are you using?

**Comment by harshithsn** [comment]
> Yes, I can open magic with your sky130A.tech. What version of magic are you using?

8.1.198

**Comment by RTimothyEdwards** [comment]
Your version of magic is three and a half years out of date so no, it isn't compatible at all with the SkyWater PDK and of course it crashes.

**Comment by harshithsn** [comment]
> Your version of magic is three and a half years out of date so no, it isn't compatible at all with the SkyWater PDK and of course it crashes.

@RTimothyEdwards Thank you sir, I just updated magic and now I can easily run magic with `sky130A.tech`

Thank You 😃🙏
